### ISSUE TITLE
AMP Support

### ISSUE THREAD

**Issue by msiefertwm** [bitfocus/companion-module-grassvalley-amp#1]
**Describe the feature**
I'd like to be able to control my Grass Valley K2 Solo 2-Channel Media Server via the AMP protocol.  Specifically, I'm looking for transport control (Play, Stop, etc).  (The protocol allows for transport control and media filing control.)

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**
The best documentation to implement is found here:
http://www.gvgdevelopers.com/concrete/apis/amp_protocol/

**Usecases**
This would be important for anyone using Grass Valley gear.  The AMP protocol is used in most of their products, so creating this would enable a number of GV devices to be used with Companion.

Thanks for considering this!

**Comment by danielmerchen** [comment]
We’ve some K2 in our systems, let me know if we can help!

**Comment by haakonnessjoen** [comment]
Geat! Please download the latest bleeding edge from https://builds.bitfocus.io/companion/ and see if it is able to control your K2's. And if not, if we could fix some way for me to connect to a K2 device for å a short while, via internet or vpn or something similar. That would be awesome :)
