### ISSUE TITLE
Grass Valley AMP Issue

### ISSUE THREAD

**Issue by Killerhands** [bitfocus/companion-module-grassvalley-amp#2]
Trying to use the AMP protocol module and for some reason when I try to send a record command it sends the initial command to connect to open the connection and connect to the right channel but won't send any subsequent messages. I was trying to use it with an ATOMOS Shogun Studio which does work via Dashboard and via our Carbonite AMP connections so I think it may be a bug?

It also seems like when I connect to PacketSender to deubg the issue the initial command to connect to the right channel is missing the padding on the number of characters descriptor. Not sure if that's associated with it at all, but just something I noticed.

**Comment by danielmerchen** [comment]
Doing a bit of packet sniffing here to see what's going on. When the instance is created for AMP it looks like it tries to send the "heads up a connection is coming" command to the receiving device but doesn't pad the correct number of bytes.

I'm testing using Vtr2 -- as that happens to be my playback channel on this system. It appears all commends are followed by a new line "\n".

What is sent by Companion (1.2 stable): "CRAT7204Vtr2"
What works: "CRAT0007204Vtr2"

So the basic syntax is CRAT (which I believe tells it to create a connection) + 4 digit interger (equal to the number of following bytes [204Vtr2 = 7 bytes]) + the actual command.

For channel 1 send: CRAT0007204Vtr1\n
For channel 2 send: CRAT0007204Vtr2\n
// I don't have a 4 channel unit to test against, but their documentation states the channel just iterates like below.
For channel 3 send: CRAT0007204Vtr3\n
For channel 4 send: CRAT0007204Vtr4\n 

The play action in companion issues a command: "CMDS00042001" -- this is the same string works for me when sending TCP to the AMP device.

When closing a connection with the AMP server it would be nice to do: STOP0000 (for example when disabling an instance.) The GV Documentation makes note that setting up and tearing down connections in unnecessary volume can cause instability or performance issues on the device.

Sending the stop action doesn't result in any packets actually being sent -- seems like something is getting stuck.

**Comment by JeffreyDavidsz** [comment]
> I didn't have any success with load clip when specifying the string/clip name - the dropdown list did populate with available clips but I wasn't able to use it to recall them just yet. I'll have to circle
> back and give the record function a try.

What it the status on this? Please file a new issue if needed

**Comment by emu0117** [comment]
The LOAD CLIP command is not working properly in T2-4k right now.
When I enter the clip name and send the command, nothing happens.
The dropdown list only shows "none".
PLAY and STOP are working.
